import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 62813
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        koneksi();
    }
    
    public Connection con;
    //public Statement stm;
    public PreparedStatement pst;
    public ResultSet rs = null;
    
    public void koneksi(){
        try {            
            Class.forName("com.mysql.cj.jdbc.Driver");
            try{ 
                 con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/tugas6_gui","root","");
            }catch (SQLException ex){
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
            }
        } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passRegis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userRegis = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        roleBoxRegis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME IN LIBRARYMU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 280, 50));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 20));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 30));

        passRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passRegisActionPerformed(evt);
            }
        });
        jPanel1.add(passRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, -1));

        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 140, -1));

        userRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegisActionPerformed(evt);
            }
        });
        jPanel1.add(userRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 250, -1));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, -1));

        roleBoxRegis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anda Mendaftar Sebagai", "Admin", "User" }));
        jPanel1.add(roleBoxRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 250, -1));

        jLabel6.setText("Sudah Memilki Akun? Registrasi Sekarang!");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 230, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passRegisActionPerformed

    private void userRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRegisActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       Register reg = new Register();
       reg.setVisible(true);
       reg.pack();
       reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
      try{
         String usr = userRegis.getText();
         String pas = passRegis.getText();
         pst = con.prepareStatement("Select * from register where userName=? and PASSWORD=?");
         pst.setString(1, usr);
         pst.setString(2, pas);
         rs = pst.executeQuery();
      
         if(rs.next() == true){
                if(roleBoxRegis.getSelectedItem().equals("Admin")){
                    JOptionPane.showMessageDialog(null, "Berhasil Login sebgai Admin");
                   DataAdmin data = new  DataAdmin();
                    data.setVisible(true);
                    data.pack();
                    data.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    //this.dispose();
                }
                if(roleBoxRegis.getSelectedItem().equals("User")){
                      JOptionPane.showMessageDialog(null, "Hallo " +  usr );
                        PeminjamanForm pinjem = new  PeminjamanForm();
                        pinjem.setVisible(true);
                        pinjem.pack();
                        pinjem.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
               }
             
         }else{
             JOptionPane.showMessageDialog(null, "Username / Password yang anda masukan SALAH");
             setKosong();
         }
      }catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    public void setKosong(){
        userRegis.setText("");
        passRegis.setText("");
        roleBoxRegis.setSelectedIndex(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passRegis;
    private javax.swing.JComboBox<String> roleBoxRegis;
    private javax.swing.JTextField userRegis;
    // End of variables declaration//GEN-END:variables
}
