import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 62813
 */
public class Register extends javax.swing.JFrame {
    public Connection con;
    //public Statement stm;
    public PreparedStatement pst;
    public ResultSet rs = null;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        koneksi();
    }
  
    public void koneksi(){
        try {            
            Class.forName("com.mysql.cj.jdbc.Driver");
            try{ 
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/tugas6_gui","root","");
            }catch (SQLException ex){
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);
            }
        } catch (ClassNotFoundException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        regisButton = new javax.swing.JButton();
        roleBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME IN LIBRARYMU");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 280, 50));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 20));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REGISTER");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 30));

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, -1));

        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 140, -1));

        userField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 250, -1));

        regisButton.setText("Register");
        regisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisButtonActionPerformed(evt);
            }
        });
        jPanel1.add(regisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, -1));

        roleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anda Mendaftar Sebagai", "Admin", "User" }));
        jPanel1.add(roleBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 250, -1));

        jLabel6.setText("Sudah Memilki Akun? Login Sekarang!");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 210, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userFieldActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Login log = new Login();
        log.setVisible(true);
        log.pack();
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void regisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisButtonActionPerformed
        
        try {
             String usre = userField.getText();
        
         pst = con.prepareStatement("Select * from register where userName=? ");
         pst.setString(1, usre);
         rs = pst.executeQuery();
             if(rs.next() == true){
                       JOptionPane.showMessageDialog(this, "Username anda sudah dipakai");
                       setKosong();
            }else{
               try {
                               String usr = userField.getText();
                               String pas = passField.getText();
                               String rl = "" + roleBox.getSelectedItem();

                               pst = con.prepareStatement("insert into register(`userName`, `PASSWORD`, `role`) values (?,?,?)");
                               pst.setString(1, usr);
                               pst.setString(2, pas);
                               pst.setString(3, rl);
                               int b = pst.executeUpdate();

                               if(pas.length() >= 8){
                                    if(rl.equals("Admin") || rl.equals("User")){
                                            JOptionPane.showMessageDialog(null, "Data anda berhasil dimasukan");
                                            setKosong();
                                    }else{
                                       JOptionPane.showMessageDialog(this, "Anda harus memlilih Pengguna");
                                   }
                               }else{
                                   JOptionPane.showMessageDialog(this, "Password minimal panjang harus 8");
                               }
                   } catch (SQLException e) {
                                Logger.getLogger(Register.class.getName()).log(Level.SEVERE,null,e);
                               }
             }
         
        } catch (Exception e) {
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
       
    }//GEN-LAST:event_regisButtonActionPerformed
    
    
    public void setKosong(){
        userField.setText("");
        passField.setText("");
        roleBox.setSelectedIndex(0);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passField;
    private javax.swing.JButton regisButton;
    private javax.swing.JComboBox<String> roleBox;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
